### ISSUE TITLE
Build on linux error 2.2.0

### ISSUE THREAD

**Issue by SergeyDjam** [crow-translate/crow-translate#52]
Hello, i building on ROSA Linux R11 crow-translation v2.2.0 and crash on error
```
/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++-64 -o playerstoppedtransition.o src/transitions/playerstoppedtransition.cpp
src/cli.cpp: In member function 'void Cli::printTranslation()':
src/cli.cpp:198:30: error: expected unqualified-id before '[' token
             for (const auto &[word, gender, translations] : it.value()) {
                              ^
src/cli.cpp:198:30: error: expected ';' before '[' token
src/cli.cpp:198:31: error: 'word' was not declared in this scope
             for (const auto &[word, gender, translations] : it.value()) {
                               ^
src/cli.cpp:198:37: error: 'gender' was not declared in this scope
             for (const auto &[word, gender, translations] : it.value()) {
                                     ^
src/cli.cpp:198:45: error: 'translations' was not declared in this scope
             for (const auto &[word, gender, translations] : it.value()) {
                                             ^
src/cli.cpp: In lambda function:
src/cli.cpp:198:59: error: expected '{' before ':' token
             for (const auto &[word, gender, translations] : it.value()) {
                                                           ^
src/cli.cpp: In member function 'void Cli::printTranslation()':
src/cli.cpp:198:59: error: expected ';' before ':' token
src/cli.cpp:198:59: error: expected primary-expression before ':' token
src/cli.cpp:198:59: error: expected ')' before ':' token
src/cli.cpp:198:59: error: expected primary-expression before ':' token
src/cli.cpp:214:30: error: expected unqualified-id before '[' token
             for (const auto &[example, description] : it.value()) {
                              ^
src/cli.cpp:214:30: error: expected ';' before '[' token
src/cli.cpp:214:31: error: 'example' was not declared in this scope
             for (const auto &[example, description] : it.value()) {
                               ^
src/cli.cpp:214:40: error: 'description' was not declared in this scope
             for (const auto &[example, description] : it.value()) {
                                        ^
src/cli.cpp: In lambda function:
src/cli.cpp:214:53: error: expected '{' before ':' token
             for (const auto &[example, description] : it.value()) {
                                                     ^
src/cli.cpp: In member function 'void Cli::printTranslation()':
src/cli.cpp:214:53: error: expected ';' before ':' token
src/cli.cpp:214:53: error: expected primary-expression before ':' token
src/cli.cpp:214:53: error: expected ')' before ':' token
src/cli.cpp:214:53: error: expected primary-expression before ':' token
g++ -c -O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -DPIC -fPIC -std=gnu++1z -Wall -W -D_REENTRANT -fPIC -DQ_TASKBAR_CONTROL_EXPORT= -DQAPPLICATION_CLASS=QApplication -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_X11EXTRAS_LIB -DQT_GUI_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I. -Isrc -Isrc/qonlinetranslator/src -Isrc/qgittag/src -Isrc/third-party/qhotkey/QHotkey -Isrc/third-party/qtaskbarcontrol -Isrc/third-party/singleapplication -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtMultimedia -isystem /usr/include/qt5/QtX11Extras -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++-64 -o settingsdialog.o src/settings/settingsdialog.cpp
make: *** [Makefile:936: cli.o] Error 1
make: *** Waiting for unfinished jobs....
error: Неверный код возврата из /var/tmp/rpm-tmp.25404 (%build)


Ошибки сборки пакетов:
    Неверный код возврата из /var/tmp/rpm-tmp.25404 (%build)
```

Qt 5.11

**Comment by Shatur95** [comment]
Hello!
What version of gcc are you using?
These errors are caused due to modern C++17 expressions.

**Comment by SergeyDjam** [comment]
Hello. 

rpm -qa | grep gcc
lib64gcc1-5.5.0_2017.10-2-rosa2016.1.x86_64
gcc-cpp-5.5.0_2017.10-2-rosa2016.1.x86_64
gcc-5.5.0_2017.10-2-rosa2016.1.x86_64
libgcc1-5.5.0_2017.10-2-rosa2016.1.x86_64
gcc-c++-5.5.0_2017.10-2-rosa2016.1.x86_64

**Comment by Shatur95** [comment]
You have a very old version of GCC. Can you install a newer version?

**Comment by Shatur95** [comment]
I assume that the issue can be closed.
