### ISSUE TITLE
Fails to build from latest master

### ISSUE THREAD

**Issue by kapsh** [crow-translate/crow-translate#46]
# Steps to reproduce

```
git clone --recursive https://github.com/crow-translate/crow-translate
cd crow-translate
qmake-qt5
make -j4
```

# Result
`make` fails with messages like 
```
/usr/x86_64-pc-linux-gnu/include/qt5/QtCore/qvector.h:607:33: error: no matching function for call to 'QExample::QExample()'
/usr/x86_64-pc-linux-gnu/include/qt5/QtCore/qvector.h:607:33: error: no matching function for call to 'QOption::QOption()'
```
[build.log](https://github.com/crow-translate/crow-translate/files/3498328/build.log)

Bisected this to c0612c51e6702b631014ec7c1d7e80e25004873a

**Comment by Shatur95** [comment]
Hmm.... Tried it just now with your PR and it builds.

Maybe you mean that you cloned repo and then rebase to c0612c51e6702b631014ec7c1d7e80e25004873a? If yes you need to downgrade submodules too. I see a problem in your log in one of them (QOnlineTranslator).

But I recommend using the most recent commit, as It is quite stable. New release will be soon, just need to improve some things :)

**Comment by kapsh** [comment]
No, I double checked that
1. My local repo has updated submodules after checkout to df85001 
2. It does not build from clean clone (as described in steps).

And this is why it's odd. Currently I am on 99788c2 and submodule is on
` 2236db5376c24c60b440d284786c58080fe74eb9 src/qonlinetranslator (1.1.2-40-g2236db5)`. Do you see anything suspicious here?

**Comment by Shatur95** [comment]
No, it's weird, on my machine clean build works.
What distro and GCC are you using?

**Comment by kapsh** [comment]
This is Exherbo Linux with GCC 8.3.0. I also checked on another (virtual) machine with Fedora 30 which has GCC 9.1.1 with the same result. -- Alexander "kapsh" Kapshunakapsh@kap.sh   15.08.2019, 14:13, "Hennadii Chernyshchyk" <notifications@github.com>:No, it's weird, on my machine clean build works.What distro and GCC are you using?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Shatur95** [comment]
Thanks! Reproduced it on live USB.

**Comment by kapsh** [comment]
Thank you for looking into this issue. Have you found the culprit? Do I have some rare edge case in my setup waiting to be fixed?

I'm asking because now build passes that point, but still fails later with these errors: [build2.log](https://github.com/crow-translate/crow-translate/files/3510916/build2.log)

**Comment by Shatur95** [comment]
Wow, missed it, sorry

**Comment by Shatur95** [comment]
It's hard to test on all platforms :)
Done.

**Comment by kapsh** [comment]
Awesome, everything builds now.
